### ISSUE TITLE
Don't give up!

### ISSUE THREAD

**Issue by hawkoon** [fatchan/jschan#123]
Take a break if you need to, after everything that happened recently. But don't give up! This is a really good project and already quite advanced. If you add .onion support and (You)s and that kind of stuff it will practically be a complete, modern imageboard package.
Personally I see what happened recently as a blessing in disguise, because it will no longer distract you with imageboard shenanigans (which was happening a little too much anyway, lately) and you can focus solely on improving the software. Thanks Thomas.

**Comment by fatchan** [comment]
Not done working on this, just a bit slower given i dont have a website full of people that I have to fix things quickly for. TOR will come, people have already suggested some ways to make it work.
