### ISSUE TITLE
Changing password is broken

### ISSUE THREAD

**Issue by hawkoon** [fatchan/jschan#124]
When I fill in all the info and click 'Change Password', nothing happens. Nothing loads or refreshes.
![broken](https://user-images.githubusercontent.com/54553501/81331347-bd670080-90a1-11ea-9334-ea01a187bab9.png)
PM2 logs say:

```
1|chan     |   <rejected> TypeError: Cannot read property 'single' of undefined
1|chan     |       at module.exports (/home/jschan/helpers/captcha/captchaverify.js:86:39)
1|chan     |       at processTicksAndRejections (internal/process/task_queues.js:97:5)
1|chan     | }
1|chan     | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
1|chan     | TypeError: Cannot read property 'single' of undefined
1|chan     |     at module.exports (/home/jschan/helpers/captcha/captchaverify.js:86:39)
1|chan     |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
1|chan     | 2020-05-07 18:28:15.013: TypeError: Cannot read property 'single' of undefined
1|chan     |     at module.exports (/home/jschan/helpers/captcha/captchaverify.js:86:39)
1|chan     |     at processTicksAndRejections (internal/process/task_queues.js:97:5) Promise {
1|chan     |   <rejected> TypeError: Cannot read property 'single' of undefined
1|chan     |       at module.exports (/home/jschan/helpers/captcha/captchaverify.js:86:39)
1|chan     |       at processTicksAndRejections (internal/process/task_queues.js:97:5)
1|chan     | }
```
Also: I have board and user account creation disabled, yet the 'Register' link still shows up at the bottom of account.html. Can you make that disappear if you have account creation disabled?

**Comment by fatchan** [comment]
Its relates to this commit, i never tested https://github.com/fatchan/jschan/commit/3bda3aa5963473369df372dd875b0c30e1f4621b
It doesnt run the process ip middleware to populate the locals with their IP object

You can either revert that or wait until this weekend and I'll push a patch 👍

**Comment by hawkoon** [comment]
‍>‍pushing commits without testing them
Yikes, please don't become Stephen Lynx-tier, you're better than that.
Anyway thanks, I'll wait for the fixes.
