### ISSUE TITLE
Board Deletion (form in global management?)

### ISSUE THREAD

**Issue by godhandgriffith** [fatchan/jschan#129]
There isn't a board deletion option in admin manage panel. I know there is a js file for that. How can I use that or add that to manage panel?

**Comment by fatchan** [comment]
The js file is for the backend file, not a frontend, the project is written in nodejs.
I can add an option to the global manage pages. A form the same as the [settings] page for board manage?

**Comment by godhandgriffith** [comment]
That would be great and very useful. Thank you so much.
