### ISSUE TITLE
Sage only email without using Forced anon

### ISSUE THREAD

**Issue by hawkoon** [fatchan/jschan#130]
I know this is already supported in jschan by using Forced anon, but I would like the name field to still be available (not forced anon) while at the same time the email field is only a sage ~~(dropdown menu?)~~ checkbox option. Vichan also supports this.

**Comment by hawkoon** [comment]
Different subject: is it possible to set a limit of X amount of threads per hour, after which thread creation becomes locked, _but_ it automatically becomes unlocked again after the hour after the last thread (or on the hour idk how you've coded it) is over?

**Comment by fatchan** [comment]
> Different subject: is it possible to set a limit of X amount of threads per hour, after which thread creation becomes locked, _but_ it automatically becomes unlocked again after the hour after the last thread (or on the hour idk how you've coded it) is over?

make separate ticket, but yes its planned.

**Comment by hawkoon** [comment]
> 
> 
> > Different subject: is it possible to set a limit of X amount of threads per hour, after which thread creation becomes locked, _but_ it automatically becomes unlocked again after the hour after the last thread (or on the hour idk how you've coded it) is over?
> 
> make separate ticket, but yes its planned.

Is a ticket for it still needed if you have that feature planned too?

**Comment by fatchan** [comment]
Sage only email thing is on dev

As for making captcha/lock mode trigger go back after the hour, there is an unstable branch ([dev-auto-reset-triggers](/fatchan/jschan/tree/dev-auto-reset-triggers)) you can try out.

**Comment by hawkoon** [comment]
>sage only email without force anon for some reason

Lol, snarky. The point of this is that the email field serves literally no other function than to sage anyway. So a 'sage box' is much more convenient than having to type it yourself. It is completely separate of the name field.
Anyway thanks, it works.
