### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by godhandgriffith** [fatchan/jschan#131]
-Board-specific settings page. I don't knwo that's a feature but it gives internal error. Settings can include changing board name/description, adding icons, etc..
-Firefox favicon. I can probably do this myself, but I don't want ot break anything.
-Overboard

**Comment by fatchan** [comment]
I cant fix the error without a log, could be same thing as #128 , or you need to `gulp migrate`.
Firefox favicon should work if you put a favicon in gulp/res/img (or gulp/res/icons? i forgot) and run gulp.
Overboard is already mentioned in another ticket and will come eventually
