### ISSUE TITLE
Disabling account and board creation is broken

### ISSUE THREAD

**Issue by hawkoon** [fatchan/jschan#135]
My main.js says:
```
	enableUserBoards: false,
	enableAccountCreation: false,
```
(meaning both account and board creation _should_ be disabled), however if you type jschansitename.com/**register.html** manually in your browser you can register an account and login no problem. What's even worse though is that although it doesn't show the option to Create a board on your account page, if you simply go to **create.html** in your browser you can successfully create your own board.
Might want to fix these serious bugs.

**Comment by fatchan** [comment]
Forgot to update the example config when I changed this before, oops.
You need to update your config here: https://github.com/fatchan/jschan/commit/51562e7cfd933e844e473984d24460cd9fdec600#r39165008

**Comment by hawkoon** [comment]
That's a lot of whoopies lately, you ok?
