### ISSUE TITLE
Opening thread without replying to the OP

### ISSUE THREAD

**Issue by hawkoon** [fatchan/jschan#136]
Which lines of code do I remove from which file to make it so that if you click [Reply] on a thread it **doesn't** automatically quote the OP post number in the post form?

**Comment by fatchan** [comment]
These parts of the frontend script control what class elements when clicked adds a quote
https://github.com/fatchan/jschan/blob/30d3f25122b738b61f8aa19205c29737958f3c31/gulp/res/js/quote.js#L84
https://github.com/fatchan/jschan/blob/30d3f25122b738b61f8aa19205c29737958f3c31/gulp/res/js/quote.js#L92

`post-quoters` is defined in the post template, and in the edit post page:
https://github.com/fatchan/jschan/blob/30d3f25122b738b61f8aa19205c29737958f3c31/views/mixins/post.pug#L50
https://github.com/fatchan/jschan/blob/d9546d6fda291378ffcd0e5766298a0410ca555e/views/pages/editpost.pug#L41

So if you want to make it not quote when clicking [reply], you could edit thost 2 lines in each template to something like:
```pug
    span
        a.post-quoters.no-decoration(href=`${postURL}#postform`) #{post.postId}
```
This will make it so only clicking the number will quote the post. Then run `pm2 reload all` and `gulp`.
lmk if that does the trick.

**Comment by hawkoon** [comment]
Ok thanks I'll fiddle with it.
