### ISSUE TITLE
Couple of errors

### ISSUE THREAD

**Issue by hawkoon** [fatchan/jschan#139]
Not sure if bugs or not but putting it out here.
1:
> 2020-05-17 08:33:07.838: Error: Command failed: gm identify: Read Exception (/home/jschan/tmp/tmp-354-1589729587697).
> gm identify: Request did not return an image.
> 
>     at ChildProcess.onExit (/home/jschan/node_modules/gm/lib/command.js:321:17)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1026:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
>   code: 1,
>   signal: null
> }

2:

> 2020-05-18 13:50:35.572: RangeError: Invalid time value
>     at Date.toISOString (<anonymous>)
>     at Object.durationString (/home/jschan/helpers/timeutils.js:84:34)
>     at module.exports (/home/jschan/models/forms/makepost.js:250:48)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async module.exports (/home/jschan/controllers/forms/makepost.js:82:3)
>

**Comment by fatchan** [comment]
1. GM couldn;t identify the image for some reason, not in the scope of this repo

2. I guess when making a post the video/audio length couldn't be converted to HH:mm:ss properly for some reason. If you can provide a link to the file elsewhere i.e. catbox, I can check it out.

Thanks!
