### ISSUE TITLE
Post histories empty through [Recent] or [Reports] pages

### ISSUE THREAD

**Issue by nate-higgers** [fatchan/jschan#142]
You have to manually go through Mod catalog or Mod Index and click on a hash to view histories otherwise trying to do it via [Recent] or [Reports] shows no posts.  Confirmed from both Board Owner and Volunteer accounts.

**Comment by fatchan** [comment]
did you change `ipHashPermLevel` in config at some point?

**Comment by hawkoon** [comment]
> 
> 
> did you change `ipHashPermLevel` in config at some point?

No, the setting has been `ipHashPermLevel: 0,` from the start and has not been changed since.

**Comment by fatchan** [comment]
This is an issue in how I handle ips/hashes being stored and displayed. Never experienced this myself because I always used -1 mode which doesnt have the bug. I will work on fixing this soon.

**Comment by fatchan** [comment]
I have tested locally on dev, resetting DB, making a few posts, reports, bans, modlog entries etc. Then checking out to the experimental branch to ensure the migration works, IP stuff isnt broken and raw IPs aren't revealed to the wrong permission level anywhere afterwards. 

Seems OK so far. This should also make ipHashPermLevel able to change without breaking everything. The only downside is the migration clears open reports and any posts attached to bans from checking "show posts in ban".  

Will merge into dev soon. I suggest backing up your db (as you should already do regularly) before trying so you can restore the db and checkout to an older revision in case something in a real instance causes it to break.

(then i can finally close all these issues and work on new features again)
