### ISSUE TITLE
Webring function is broken

### ISSUE THREAD

**Issue by hawkoon** [fatchan/jschan#145]
I've changed `enableWebring:` to `true` in the main.js config and added and edited `webring.json` in `/jschan/configs/` (basically only adding two sites to follow and changed the logo to my site's favicon location). A `gulp` and `pm2 reload all` however **do not** make the relevant webring boards appear, and sitename.com/webring.json also gives a **404**.

**Comment by hawkoon** [comment]
From another user:

> Okay, I've played around with it a bit. You should see "updating webring" logs in schedules-out-*.log, if not it doesn't even try to update the webring. It should also create a static/json/webring.json file with all the local boards. Now it either doesn't create it as https://zchan.cc/webring.json returns 404, or something is wrong with your nginx.conf.
> Somewhy I had to change the pug files because it complained about redeclaring variables, but after that when I had a mostly working ui, interestingly I have "+ Webring" text next to "Boards" in the header, even without actually enabling webring. For me it looks like views/includes/navbar.pug unconditionally includes it, did you edit it out or are you using an old version of jschan?
> The only thing that doesn't work is actually listing the webring boards in the board list, turns out this commit fucks up webring importing:
> https://github.com/fatchan/jschan/commit/fbc4661ffc6b9ed1a7bdd84779b850f5bcfa35a9
> (that nice aggregate doesn't do dogshit, but it works in mongo cli, and my non-existing mongo knowledge ends here. Reverting the commit fixes the issue for me...)
> So yeah, while webring support is broken in current jschan, something is even more broken at zchan. Double check whether configs/webring.json is a valid json, because the example is NOT (but you should get an ugly exception in the log if it's not).

**Comment by hawkoon** [comment]
From another user:

> Okay, I've played around with it a bit. You should see "updating webring" logs in schedules-out-*.log, if not it doesn't even try to update the webring. It should also create a static/json/webring.json file with all the local boards. Now it either doesn't create it as https://site.com/webring.json returns 404, or something is wrong with your nginx.conf.
> Somewhy I had to change the pug files because it complained about redeclaring variables, but after that when I had a mostly working ui, interestingly I have "+ Webring" text next to "Boards" in the header, even without actually enabling webring. For me it looks like views/includes/navbar.pug unconditionally includes it, did you edit it out or are you using an old version of jschan?
> The only thing that doesn't work is actually listing the webring boards in the board list, turns out this commit fucks up webring importing:
> https://github.com/fatchan/jschan/commit/fbc4661ffc6b9ed1a7bdd84779b850f5bcfa35a9
> (that nice aggregate doesn't do dogshit, but it works in mongo cli, and my non-existing mongo knowledge ends here. Reverting the commit fixes the issue for me...)
> So yeah, while webring support is broken in current jschan, something is even more broken at your site. Double check whether configs/webring.json is a valid json, because the example is NOT (but you should get an ugly exception in the log if it's not).

**Comment by fatchan** [comment]
If you set it to true and it isnt working, I suspect there are some errors in the schedules causing it to not output webring.json. `pm2 logs schedules` (then reload and see if anything comes up)
> For me it looks like views/includes/navbar.pug unconditionally includes it, did you edit it out or are you using an old version of jschan?
This is probably true, i think i hardcoded it in for my site and never made it follow the configs after I closed down.
> this commit fucks up webring importing: fbc4661 (that nice aggregate doesn't do dogshit, but it works in mongo cli
Ill have to check why that aggregate apparently doesnt work in the schedules, but works in mongo CLI.
For now yes you can probably revert that commit, you just lose socks proxy support (not like it matters if webring is broken)
I will check the example config also tonight to make sure its correct.

**Comment by fatchan** [comment]
Ok, that aggregation throws `MongoError: Invalid Operation, no operations specified`, because its trying to operate on an empty array. This can happen if it didn't fetch any webring boards because of:
- An empty or dead "following" list
- A dead or incorrectly configured proxy (if using the `proxy` option)

As for the example config, I removed a stray `,`.

Trying now with https://anon.cafe/webring.json in the following list, it successfully traverses the webring.
![image](https://user-images.githubusercontent.com/18641559/83006935-48f70000-a056-11ea-90ec-d2e0c7182324.png)

**Comment by hawkoon** [comment]
Webring is still broken after the latest commit. When manually deleting `webring.json` from `/static/json/` but still keeping the (changed) webring config in the configs folder and then `gulp` `pm2 reload all` does not rebuild the webring.json file in the /static/json/ folder.

**Comment by hawkoon** [comment]
I got sitename.com/webring.json working now, however the boards of the 2 websites I'm following are **not** showing up on my site's /boards.html page.

**Comment by fatchan** [comment]
Are you on dev branch? I havent done anything on master in while apart from dependabot merges. Once I get my own site going again and I'm happy with putting changes back to master I will.

**Comment by hawkoon** [comment]
> Are you on dev branch? I havent done anything on master in while apart from dependabot merges. Once I get my own site going again and I'm happy with putting changes back to master I will.

Yes I've been on the dev branch since you first created it.

**Comment by hawkoon** [comment]
LOL! RIP you, because 82eb07e indeed fixed it.
