### ISSUE TITLE
The rainbow '+Webring' thingy doesn't show up on custom pages

### ISSUE THREAD

**Issue by hawkoon** [fatchan/jschan#149]
Not sure if a bug or a feature, but the rainbow '+Webring' thingy doesn't show up on the custom pages (FAQ and Rules), while it does show up on all the other pages (Home, News, Account etc). See attachment for the difference. Seems an inconsistency in design.
![difference](https://user-images.githubusercontent.com/54553501/83330651-dc1b7a00-a290-11ea-866f-0553ebb47378.png)

**Comment by fatchan** [comment]
will fix in the morning, cheers.
