### ISSUE TITLE
Which branch to use?

### ISSUE THREAD

**Issue by hawkoon** [fatchan/jschan#154]
It's getting kind of confusing now with 3 different branches with different commits for each branch. I'm on `dev` at the moment.

**Comment by fatchan** [comment]
dont worry for now. soon ill merge everything back into dev and then master

**Comment by hawkoon** [comment]
Ok cool. There's a new version of NPM available by the way.
![npm](https://user-images.githubusercontent.com/54553501/83714569-6d8d4200-a62b-11ea-85a8-4786cb7aaa16.png)
