### ISSUE TITLE
IDs changed?

### ISSUE THREAD

**Issue by hawkoon** [fatchan/jschan#158]
Did the latest commits in the `dev` branch have any changes regarding poster IDs? I pulled the latest commit and gulp/pm2'd and it seems users in a giant sticky on a board now have different IDs using the same IP.

**Comment by fatchan** [comment]
Yeah it was caused by the ip changes recently, just a small tweak and they should be back to how they were before.

**Comment by hawkoon** [comment]
I applied the fix but IDs of posters with the same IP in the thread still haven't changed back to their old ones.

**Comment by fatchan** [comment]
I got an email about a comment, (maybe you deleted it?) saying the IDs were still not the same. Could be related to #161 but they should be fixed otherwise. Unless you changed the salt in configs.
