### ISSUE TITLE
BMPs are broken

### ISSUE THREAD

**Issue by hawkoon** [fatchan/jschan#165]
.bmp files upload fine and they get thumbnailed, however:
1. They don't expand when you click on them
2. Right-click opening the actual file in a new tab gives a '404 not found'

**Comment by fatchan** [comment]
BMP was missing from the nginx config. To fix, add the extension to your config like this:
https://github.com/fatchan/jschan/commit/cb57b72744ecc647fb64f856a0a104d5127dc020#diff-d22ef4b564f299411347c8c79e955756R114
