### ISSUE TITLE
The ever-evolving list of TODOs

### ISSUE THREAD

**Issue by fatchan** [fatchan/jschan#2]
closed and separated into other issues

**Comment by DonaldTsang** [comment]
Progress? Also how are you doing?

**Comment by fatchan** [comment]
Sorry late reply, and things have been going OK. I have been removing things from the list slowly as I complete them, only using checkboxes for stuff that is in-progress  or recently finished.

I am on holiday right now and getting close to graduating university so forgive the slowness. There has been some progress on the "8chan" feature list issue. I keep forgetting to add the references keyword to my commits though :sweat_smile: Next week I will add a few things like marking inactive boards claimable and adding post editing by staff :smile:
