### ISSUE TITLE
JSON API

### ISSUE THREAD

**Issue by fatchan** [fatchan/jschan#24]
need to make read-only JSON API and make it compatible with format of other sites.

Gonna be a major change since i would need to change name of properties in database and references to them elsewhere in code and views. This is because i want to return raw query data from the db as easily as possible without having to change key names before returning.

**Comment by fatchan** [comment]
Will do this soon. Gonna make the JSON save to json files and delete alongside when deleting html. Just need to make sure database projections are all safe, e.g. not revealign thread id salts, post passwords, ip(or eventually hashes), etc in api. I dont think it will since I do projections, just need to make sure. Also should probably project to remove unnecessary fields in more places.

**Comment by DonaldTsang** [comment]
So should we grab a list of other website and application info for this?
- https://f-droid.org/en/packages/org.floens.chan/ (most up to date)
- https://f-droid.org/en/packages/bus.chio.wishmaster/ (2018 Feb)
- https://f-droid.org/en/packages/com.luorrak.ouroboros/ (2016 Sep)

**Comment by fatchan** [comment]
I personally use an overchan fork https://github.com/overchan-project/Overchan-Android

**Comment by fatchan** [comment]
143ea5a0a05e234723d7235c474cbcb168df4b4b

**Comment by DonaldTsang** [comment]
@fatchan so it might be a good idea to support as many mobile browsers as necessary as we don't know which one is the "official" one for 4chan, 8chan and endchan.

**Comment by fatchan** [comment]
I would be most interested in forking and PR'ing Overchan. Firstly because I use it, but it supports most imageboard softwares:
- tinyboard/vichan/infinity includes forks like OpenIB (8chan), lainchan (lainchan) and NPFchan (mlpol and vch)
- lynxchan (i think there is a fork because of [kohlchan](https://kohlchan.net)
- tons of other sites have been made compatible

**Comment by DonaldTsang** [comment]
@fatchan if that is the main direction we are going, I would recommend OverDev to please update the app on F-Droid and Google Play (the former is preferable).

**Comment by fatchan** [comment]
Closing some issues, going to be using issues more properly. Will create a separate issue when I get around to making compatible with some mobile app.
