### ISSUE TITLE
8chan-like features

### ISSUE THREAD

**Issue by DonaldTsang** [fatchan/jschan#39]
- [x] User-created boards
- [x] Group/Community moderation on boards
- [x] Registered accounts
  - [x] Board Owners (person who owns the board)
  - [x] Board Volunteers (person who helps the BO)
- [x] Board tags
  - [x] use in board searching
- [x] Board names (alphanumeric)
  - [x] case insensitive form `cyberpunk` (used in URLs)
  - [x] display form `/CyberPunk/` (as displays)
- [x] Board announcements a.k.a. "red bar of text on the top of the page"
- [ ] Board links to other boards a.k.a. "Sister/Collaborate boards"
   - See https://8ch.net/fringe and https://8ch.net/rule34
- [x] Moderation activity
- [ ] board claiming
- [x] board transfer
- [x] File support
  - [ ] Music (MP3, OGG/OGA/MOGG, OPUS, APE, FLAC, WAV, AAC/M4A/3GP, AIFF/AIF/AIFC, WMA/WMV, ALAC/M4A/CAF, etc.)
  - [x] Video (MP4/M4P/M4V, MKV, WMV, MOV/QT, AVI, FLV, OGV,  MPG/MP2/MPEG/MPE/MPV etc.)
  - [x] Images (APNG, WEBP, FLIF, HEIF, AVIF etc.)
  - [ ] Ebooks (PDF, EPUB, MOBI, DJVU)
- [ ] GET scripts (for /sp/)
- [x] Cycled Threads (deletes old posts except OP in order to keep it from getting bumplocked)
  - [ ] User-invoked
  - [x] Moderation-invoked (by Owner or Volunteer)
- [x] Top Stickied Threads (must be Moderation-invoked)
- [ ] Bottom Stickied Threads (must be Moderation-invoked)
- [x] Wiki/FAQ
- [ ] Board flags (255 flags per board)
- [x]  Board banners
- [x] Board ranking system
  - [x] Most active boards (based on post count per hour)
  - [x] Most popular boards (based on users per day)
- [x] Minimum character count per OP
- [x] Minimum image count per OP
- [ ] archives
  - [ ] Custom in-house archives
  - [ ] Usage of archive.fo
- [ ] Meta-boards (see https://nerv.8ch.net/tech/cyber/g/sudo/prog/sci/) 
- [x] Word filters
  - [x] Auto word ban (for spam)
  - [ ] Word filters/translators (for censorship/obfuscation)
- [x] Report mechanism
  - [x] Report to local board moderation
  - [x] Report to global moderation
  - [ ] Ease of moderation through checking all posts from one ID
  - [ ] Ease of moderation through checking all posts with similar names or other markers
- [ ] Video embedding
  - [ ] Re-route YouTube videos to invidio.us
- User ID
  - Unique ID hash for each board (requires a salt for every board)
  - [x] Unique ID hash for each thread (requires a salt for every thread)
  - ID representation as psuedo-names (see http://worrydream.com/tripphrase/)
- [x] Dice roll like  https://app.roll20.net/assets/dengine.js?v=123 
- [ ] File boards (see http://boards.4chan.org/f/ and https://8ch.net/tdt/ ) 

needs client scripts:
- [ ] (you) counter or highlighter
- [x] Tab icon alerts
  - [ ] blinks/changes to alert thread activity
  - [x] Tab title has a number with parentheses indicating number of new posts
  - [ ] Tab title has an exclamation point indicating "slid" thread
- [x] Hide mechanism
  - [x] Hide singular post
  - [x] Hide by ID
  - [ ] Hide by Name or Flag
  - [ ] Hide by keyword in text

**Comment by fatchan** [comment]
Comments about everything:
- [ ] User-created boards
    - would need to add a page where boards are created and modify the permissions checking middleware in a few places. pretty big one.
- [ ] Group/Community moderation on boards
    - volunteers/assigned moderators would be possible once the above is done.
- [x] Registered accounts
    - actually this already exists (/register.html), but currently only the default admin account has moderation power.
- [ ] Board tags for use in board searching
    - yes this is possible, just embed an array of tags in each board document. i think mongodb can index that.
- [ ] Board names (alphanumeric)
  - [ ] case insensitive form `cyberpunk` (used in URLs)
  - [ ] display form `/CyberPunk/` (as displays)
    - this is possible. would be a simple setting in the board manage page
- [ ] Board announcements a.k.a. "red bar of text on the top of the page"
    - this is possible. could even allow formatting similar to posts
- [ ] Board links to other boards a.k.a. "Sister/Collaborate boards"
    - there is cross-board quotes e.g. >>>/a/, maybe these links would be added to announcements. not so sure about making it an independent feature
- [ ] Moderation activity
    - yes mod logs/audit logs are planned
- [ ] board claiming/transfer
    - this would go alongside user board creation. not going to think too deep into this yet
- [ ] File support
  - [ ] Music (MP3, OPUS, OGG, WAV, FLAC etc.)
        - sure, this could be added
  - [x] Video (MP4, WEBM, MKV etc.)
  - [x] Images (APNG, WEBP, FLIF, HEIF, AVIF etc.)
  - [ ] Ebooks (PDF, EPUB, MOBI, DJVU)
        - would have to see what libs exist for this, how fast they are and how they handle thumbnails
- [ ] GET scripts (for /sp/)
    - i need some clarification, not really sure what this means.
- [x] Cycled Threads
- [x] Top Anchored Threads
    - do you mean sticky threads?
- [ ] Bottom Anchored Threads
    - there are anchored threads, but not sure what you mean by "bottom anchored", anchoring simply stops it being bumped.
- [ ] Wiki/FAQ
    - once there is more progress and things are set in stone, sure.

**Comment by DonaldTsang** [comment]
> there is cross-board quotes e.g. >>>/a/, maybe these links would be added to announcements. not so sure about making it an independent feature

I meant how board A can be linked to board B through something similar to FAQ/Wiki but is on the index page.

> (ebooks) would have to see what libs exist for this, how fast they are and how they handle thumbnails

Or you can use the paperclip method on 8chan or lainchan, no specific thumbnail , just a paperclip

>(GET) i need some clarification, not really sure what this means.

4chan history 101: People like their posts to be alerted with "dubs" "trips" "quads"... (repeated digits at the end) and "straights" (consecutive numbers at the end) See: https://8ch.net/4get

> there are anchored threads, but not sure what you mean by "bottom anchored", anchoring simply stops it being bumped.

I meant bottom stickied instead of top stickied

**Comment by fatchan** [comment]
> I meant how board A can be linked to board B through something similar to FAQ/Wiki but is on the index page.
Sure, that can be done

> 4chan history 101: People like their posts to be alerted with "dubs" "trips" "quads"... (repeated digits at the end) and "straights" (consecutive numbers at the end) See: https://8ch.net/4get

I understand that much, but afaik people just try to post when they _think_ a GET will occur because:
1. cant estimate based on post rate (since many people will try and post, increasing the post rate before it happens)
2. there is no way to post with a specific number, or get a live feed of numbers, so a script would just refresh the page (or json) quickly and find the highest post number.
I thought users make the GET scripts, its not really built into the software itself. But if people make them i dont mind.

> Or you can use the paperclip method on 8chan or lainchan, no specific thumbnail , just a paperclip

Yeah that would be fine. thumbing PDFs would be almost pointless anyway.

> I meant bottom stickied instead of top stickied

So it just stays on the last page? But it doesnt get pruned when a new thread is made? I probably will deny this as a feature since it doesnt seem very appealing to me. I will weigh up complexity added vs. gain but for now, its a no.

**Comment by DonaldTsang** [comment]
@fatchan about file-hash based thumbnails...
- Ink Blots https://github.com/stuartpb/hashblot
- Bubbles https://github.com/dakridge/identicon
- Circular https://github.com/ea7ababe/identicon
- Triangles https://github.com/Mailea/origamicons

**Comment by fatchan** [comment]
What purpose would file-hash based thumbnails serve? If the image already has a thumbnail

Only files like audio and ebooks (which do not have thubnails) could benefit from this, and I would rather have audio waveforms or thumbnails of the ebook for those.

Maybe I misunderstood

**Comment by DonaldTsang** [comment]
@fatchan maybe use it as a fall-back? Also I don't trust audio waveform as every piece of audio has different lengths, spectrogram would be slightly better for audio. video has thumbnails, some books does but some don't... the only thing I can think of is archive files.
Check the list again, I have exhausted all features.

**Comment by fatchan** [comment]
Yeah it could be a fallback. Sorry im not knowledgeable about audio so I dont really know the difference of waveform/spectrogram. I just know there is some visual representation of them. Whichever works.

And i updated the other comment with more comments about features, i think i got them all now.

**Comment by DonaldTsang** [comment]
@fatchan about user ID using names... take a look at
- https://github.com/nabetama/gimei/blob/master/gimei/data/names.yml 500 surnames and ~13K given names with overlaps in sounds for the given name
- https://github.com/sterpe/japanese-name-generator/tree/master/data/names 1262 surnames and 3957 give names in romanji

**Comment by DonaldTsang** [comment]
@fatchan please read https://github.com/lainchan/lainchan/issues/153

**Comment by fatchan** [comment]
a tally:
- [x] moderation dashboard
- [ ] new board creation
- [ ] board deletion 
    - [x] and editing
- [x] uses database
- [ ] user management
- [ ] themes or extensions
- [ ] reporting system / log
- [ ] moderation log
- [ ] ban list
- [ ] ban appeals
- [ ] search
- [ ] configuration editor
- [ ] user notes
- [ ] extensions for donate page
- [ ] extensions for stream page
- [ ] extensions for irc page
- [ ] extensions for rules page
- [x] name, email, subject, spoiler image, file ~~,oekaki~~
- [x] trip codes
- [x] sticky, lock
- [ ] raw html
- [x] file / post deletion and password
- [x] banners support
- [ ] customisable header support
- [ ] moderation actions
    - [x] delete, delete by ip, delete by ip all boards, ban, ban and delete, sticky, sage, lock
    - [ ] unsticky, move, edit (actually i need to add also unlock and unsage/unanchor)
- [x] support for post formatting
- [x] support for reply linking
- [x] image / file upload
- [x] thumbnail image support
- [ ] ddt support for layer ? (idk whats this)
- [ ] ImgOps iqdb (easy)
- [ ] word filters
- [ ] word / phrase blocking
- [x] anonymous naming scheme (it has anon name and configurable default. maybe they mean multiple random names?)
- [ ] api probably 4chan api compatible or similar
- [x] catalog extension
- [ ] overboard extensions
- [ ] recent posts (wouldnt be hard)
- [x] css themes 
- [ ] board customization (what exactly is this apart from themes and board settings?)
- [x] works with and without JavaScript (you bet. lol)
- [ ] board aliases 
- [ ] keyboard navigation (accesskeys in forms?)
- [ ] thread merge
- [ ] auto IP note generation 
- [ ] multiple file upload using URLs
- [ ] server side syntax highlighting
- is performant and secure
- hackable (easy to extend, modify and customize)
Last 2 remain to be tested and seen

I think the first 5-10 are pretty important key features that I will work on next. Thanks for finding that info. Definitely alot of work to do. I might merge this into my OP and delete comment tomorrow morning.

**Comment by DonaldTsang** [comment]
@fatchan you are a hero, brother. Can't believe you can aim that high

**Comment by fatchan** [comment]
Mostly moved to other issues and reorganised. Will revisit if something major I missed is highly requested.

**Comment by DonaldTsang** [comment]
Got it.
