### ISSUE TITLE
Cross-collaboration with Kotoba

### ISSUE THREAD

**Issue by DonaldTsang** [fatchan/jschan#40]
Things to learn from Kotoba:
- Simplicity is key
- Standardization of HTML elements for compatibility with other applications
https://github.com/WagonOfDoubt/kotoba.js/issues/3

**Comment by fatchan** [comment]
I agree with simplicity, but standardization of HTML (in terms of exact markup) is not important. Only the general appearance for users. For a "standard format" maybe JSON is more important, but even for that I will just makr a fork and PR to overchan to support jschan. Also from their readme "generate valid HTML5, use semantic elements and provide machine-readable output as much as possible." is VERY important and at _some point_ I will implement it.

But I wouldnt do a collaboration at this point kotoba. This project is its own thing.

**Comment by DonaldTsang** [comment]
@fatchan please take a ReadME:
https://github.com/WagonOfDoubt/kotoba.js/blob/master/README.md
> Frontend should be compatible with most standard Wakaba/Kusaba based imageboards, therefore third-party code like Dollchan Extension Tools and Overchan-Android require minimal modifications.

This is a key for cross-compatibility.
