### ISSUE TITLE
2 Factor Authentication

### ISSUE THREAD

**Issue by DonaldTsang** [fatchan/jschan#42]
This would be useful for both core board and autonomous board management 
- Email + referral email
    - Requires email server (easier)
    - Has well-established flask plugins
    - Could rely on cock.li service (might need negotiation)
- Mobile Application (e.g. Telegram, RocketChat)+ PIN Code
    - Requires application bot (harder)
    - Do not use Whatsapp, Messenger, Twitter or SMS
    - Might need further refinements on what software to use or not to use

**Comment by fatchan** [comment]
No plans for this yet, a bit broad
