### ISSUE TITLE
Alternative Captchas

### ISSUE THREAD

**Issue by DonaldTsang** [fatchan/jschan#43]
- "Faptcha" or other topic-related captcha
- Motion/Animated Captcha
- Sound/Audio Captcha
- Math Captcha

**Comment by fatchan** [comment]
If "faptcha" is similar concept as meguca.org's "captchouli", then probably no.

The others are all fine. Im sure there is some way to generate them. Deeeeeefinitely this is low priority though.

**Comment by DonaldTsang** [comment]
@fatchan it is just something auxiliary when compared to the 8chan list I agree.
