### ISSUE TITLE
Funding Timer

### ISSUE THREAD

**Issue by DonaldTsang** [fatchan/jschan#44]
Something similar to https://codepen.io/shristi-uiDeveloper/pen/OYOpMw
- Used to mark how much Patreon/SubscribeStar money you get for the board
- Used to mark how much cryptocurrency has been gathered for the board
- Used to mark how far away it is away from the website funding deadline

**Comment by fatchan** [comment]
Sure, any site owner can add one, but tracking of payments is out of scope. 

At some point I will add instructions how to make a custom page using a pug template and build it with `gulp`, so site admins can create and update additional pages (faq, about, privacy policy, etc). This could be put on one of those pages.

**Comment by DonaldTsang** [comment]
@fatchan was hoping the funding timer to be a front-page thing that can help some admins (see yiff.party's model ... yeah I felt dirty saying that)

**Comment by fatchan** [comment]
From the donation tracker on their site: "Please note: this tracker is updated manually—don't worry if your donation doesn't show up immediately!" so yes it can be added but there is no facility to actually track them so it would be manually updated.

**Comment by DonaldTsang** [comment]
@fatchan that was the CSS designs, not the actual code, for the actual code I would try and pull up their website's info
For Patreon: https://docs.patreon.com/#api-libraries
For SubscribeStar we will have to wait

**Comment by fatchan** [comment]
Yes there can be an interface for tracking payments, and just have an interface defined so people can make for different providers. I have worked with patreon before.

**Comment by DonaldTsang** [comment]
@fatchan so is it possible to turn this feature into a front page component so people can turn it on/off?
